### ISSUE TITLE
with oh-my-zsh  PS1 don't work

### ISSUE THREAD

**Issue by oliveagle** [pwoolcoc/goenv#10]
3 points on pic:

1. with oh-my-zsh PS1 don't work
2. without oh-my-zsh, PS1 under zsh is still not good
3. virtuanenv under oh-my-zsh works pretty well. 

![qq20150129-6](https://cloud.githubusercontent.com/assets/2270205/5957746/145afd94-a7f8-11e4-82d3-50fc1c141639.png)

**Comment by pwoolcoc** [comment]
Thanks for reporting this. I realized a while back that setting the `$PS1` was particularly error-prone, and meant to do something about it. Instead of trying to make it work with every shell, I ended up just punting and leaving the prompt modification to the user.

Currently, the `goenv` script will set an environment variable `$GOENV` in the subshell that it launches. This allows the user to, in their shell config, detect when they are running in a `goenv` subshell, and modify their prompt however they would like.

For example, in my `.bashrc`, I modify my prompt like so:

    function _goenv {
        [ -n "${GOENV}" ] && echo "(golang-${GOENV}) " && return
    }

    PS1='$(_goenv)\u@\h \w $(__git_ps1 "${1:-(%s)} ")$(prompt_char) '

The important part of the `$PS1` is the beginning, `$(_goenv)`. It means that when I am running in a `goenv` subshell, it will prepend the string `(golang-$GOENV) ` to my prompt.

You should be able to do something similar either in your `.zshrc`, or in a `oh-my-zsh` plugin, but I do not use `zsh` or `oh-my-zsh` so I can't really help you there.

**Comment by oliveagle** [comment]
great, thx.  

```bash
# in your-own-theme.zsh-theme

_goenv() {
    [ -n "${GOENV}" ] && echo "(golang-${GOENV}) " && return
}

PROMPT='$(_goenv)$fg[green]%n %{$fg_bold[green]%}${PWD/#$HOME/~}%{$reset_color%}$(git_prompt_info) [%{$fg_bold[red]%}%*%{$reset_color%}]
$ '
```

![qq20150129-7](https://cloud.githubusercontent.com/assets/2270205/5960613/b80ae134-a811-11e4-916f-949f05e8cea5.png)
